---
apiVersion: {{ include "deploymentversion" .}}
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: hubble-ui
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      k8s-app: hubble-ui
  template:
    metadata:
      labels:
        k8s-app: hubble-ui
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: 1001
      {{- end }}
      serviceAccountName: hubble-ui
      serviceAccount: hubble-ui
      containers:
        - name: hubble-ui
          image: {{ index .Values.global.images "hubble-ui" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: HUBBLE
              value: "true"
            - name: HUBBLE_SERVICE
              value: "hubble-relay"
            - name: HUBBLE_PORT
              value: "80"
          ports:
            - containerPort: 12000
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 64Mi
