---
apiVersion: {{ include "deploymentversion" .}}
kind: Deployment
metadata:
  name: hubble-ui
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: hubble-ui
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      k8s-app: hubble-ui
  template:
    metadata:
      labels:
        k8s-app: hubble-ui
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: 1001
      {{- end }}
      serviceAccountName: hubble-ui
      serviceAccount: hubble-ui
      containers:
        - name: frontend
          image: {{ index .Values.global.images "hubble-ui" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 64Mi
        - name: backend
          image: {{ index .Values.global.images "hubble-ui-backend" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          env:
            - name: EVENTS_SERVER_PORT
              value: "8090"
            - name: FLOWS_API_ADDR
              value: "hubble-relay:80"
          ports:
            - name: grpc
              containerPort: 8090
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 64Mi
        - name: proxy
          image: {{ index .Values.global.images "envoy" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - name: http
              containerPort: 12000
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 64Mi
          command: ["envoy"]
          args:
          - -c
          - /etc/envoy.yaml
          - -l
          - info
          volumeMounts:
          - name: hubble-ui-envoy-yaml
            mountPath: /etc/envoy.yaml
            subPath: envoy.yaml
      volumes:
      - name: hubble-ui-envoy-yaml
        configMap:
          name: hubble-ui-envoy
