---
apiVersion: {{ include "deploymentversion" .}}
kind: Deployment
metadata:
  name: hubble-ui
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: hubble-ui
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      k8s-app: hubble-ui
  template:
    metadata:
      labels:
        k8s-app: hubble-ui
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      {{- end }}
      serviceAccountName: hubble-ui
      serviceAccount: hubble-ui
      containers:
        - name: frontend
          image: {{ index .Values.global.images "hubble-ui" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
          - name: http
            containerPort: 8081
          volumeMounts:
            - name: hubble-ui-nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 64Mi
        - name: backend
          image: {{ index .Values.global.images "hubble-ui-backend" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          env:
            - name: EVENTS_SERVER_PORT
              value: "8090"
            - name: FLOWS_API_ADDR
              value: "hubble-relay:80"
          ports:
            - name: grpc
              containerPort: 8090
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 64Mi
      volumes:
      - configMap:
          defaultMode: 420
          name: hubble-ui-nginx
        name: hubble-ui-nginx-conf
