apiVersion: {{ include "deploymentversion" .}}
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.numReplicas }}
  selector:
    matchLabels:
      k8s-app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Chart.Name }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "k8s-app"
                  operator: In
                  values:
                    - cilium
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: hubble-relay
          image: {{ index .Values.global.images "hubble-relay" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command:
          - "hubble-relay"
          args:
          - "serve"
          ports:
          - name: grpc
            containerPort: {{ .Values.listenPort }}
          readinessProbe:
            tcpSocket:
              port: grpc
          livenessProbe:
            tcpSocket:
              port: grpc
{{- if .Values.resources }}
          resources:
{{- toYaml .Values.resources | trim | nindent 10 }}
{{- end }}
          volumeMounts:
          - mountPath: {{ dir .Values.global.hubble.socketPath }}
            name: hubble-sock-dir
            readOnly: true
          - mountPath: /etc/hubble-relay
            name: config
            readOnly: true
          - mountPath: /var/lib/hubble-relay/tls
            name: tls
            readOnly: true
      restartPolicy: Always
      serviceAccountName: hubble-relay
      terminationGracePeriodSeconds: 0
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: {{ dir .Values.global.hubble.socketPath }}
          type: Directory
        name: hubble-sock-dir
      - configMap:
          name: hubble-relay-config
          items:
          - key: config.yaml
            path: config.yaml
        name: config
      - projected:
          sources:
          - secret:
              name: hubble-relay-client-certs
              items:
                - key: ca.crt
                  path: hubble-server-ca.crt
                - key: tls.crt
                  path: client.crt
                - key: tls.key
                  path: client.key
        name: tls

