{{- if .Values.ui.enabled }}
---
kind: Deployment
apiVersion: {{ include "deploymentversion" . }}
metadata:
  namespace: {{ .Release.Namespace }}
  name: hubble-ui
  labels:
    gardener.cloud/role: system-component
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      k8s-app: hubble-ui
  template:
    metadata:
      labels:
        k8s-app: hubble-ui
    spec:
      {{- if .Values.ui.priorityClassName }}
      priorityClassName: {{ .Values.ui.priorityClassName }}
      {{- end }}
      serviceAccountName: hubble-ui
      containers:
        - name: hubble-ui
          image: {{ index .Values.global.images "hubble-ui" }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: HUBBLE
              value: "true"
            - name: HUBBLE_SERVICE
              value: "hubble-grpc.{{ .Release.Namespace }}.svc.{{ .Values.ui.clusterDomain }}"
            - name: HUBBLE_PORT
              value: "50051"
          ports:
            - containerPort: 12000
              name: http
          resources:
            {{- toYaml .Values.ui.resources | trim | nindent 12 }}
{{- end }}
