{{- if .Values.validateCNPs }}
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: cilium-pre-flight-check
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: cilium-pre-flight-check-deployment
  template:
    metadata:
      labels:
        k8s-app: cilium-pre-flight-check-deployment
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "k8s-app"
                operator: In
                values:
                - cilium
            topologyKey: "kubernetes.io/hostname"
      containers:
        image: {{ index .Values.global.images "cilium-preflight" }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        name: cnp-validator
        command: ["/bin/sh"]
        args:
        - -c
        - "cilium preflight validate-cnp && touch /tmp/ready-validate-cnp && sleep 1h"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/ready-validate-cnp
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready-validate-cnp
          initialDelaySeconds: 5
          periodSeconds: 5
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: cilium
      serviceAccountName: cilium
      terminationGracePeriodSeconds: 1
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      - key: CriticalAddonsOnly
        operator: "Exists"
{{- end }}